version: '3.8'

services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.0
    container_name: filebeat_pihole
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    user: root
    volumes:
      - ${DOCKER_DIR}/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ${DOCKER_DIR}/pihole/pihole-configs:/etc/pihole:ro
      - ${DOCKER_DIR}/pihole/dnsmasq.d-configs:/etc/dnsmasq.d:ro
      - ${DOCKER_DIR}/pihole/logs:/pihole-logs:ro
    environment:
      - TZ=${TZ}
      - strict.perms=false
