version: "3.8"
services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    ports:
      - "8000:8000/tcp"
      - "9000:9000/tcp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_DIR}/portainer:/data
    restart: always
    environment:
      PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    networks:
      - bridge

networks:
  bridge:
    driver: bridge
