version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: matomo_db
    restart: always
    security_opt:
      - no-new-privileges:true
    command: --max-allowed-packet=64MB
    environment:
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${MATOMO_DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MATOMO_DB_NAME}
      - MYSQL_USER=${MATOMO_DB_USER}
      - MYSQL_PASSWORD=${MATOMO_DB_PASSWORD}
    volumes:
      - ${DOCKER_DIR}/matomo/db:/var/lib/mysql

  app:
    image: matomo:latest
    container_name: matomo_app
    restart: always
    security_opt:
      - no-new-privileges:true
    depends_on:
      - db
    environment:
      - TZ=${TZ}
      - MATOMO_DATABASE_HOST=db
      - MATOMO_DATABASE_ADAPTER=mysql
      - MATOMO_DATABASE_TABLES_PREFIX=matomo_
      - MATOMO_DATABASE_USERNAME=${MATOMO_DB_USER}
      - MATOMO_DATABASE_PASSWORD=${MATOMO_DB_PASSWORD}
      - MATOMO_DATABASE_DBNAME=${MATOMO_DB_NAME}
    volumes:
      - ${DOCKER_DIR}/matomo/html:/var/www/html
    ports:
      - "8597:80"
