name: SBOM Generation Pipeline

on:
  schedule:
    # Generate SBOM weekly every Monday at 3 AM UTC
    - cron: '0 3 * * 1'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-sbom:
    name: Generate Software Bill of Materials
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sudo sh -s -- -b /usr/local/bin

      - name: Extract container images
        id: extract-images
        run: |
          echo "Extracting container images from Docker Compose files..."
          IMAGES=""

          for compose_file in $(find . -name "docker-compose.yml" -o -name "docker-compose.yaml"); do
            echo "Processing: $compose_file"
            file_images=$(grep -E "^\s*image:" "$compose_file" | sed 's/.*image://g' | tr -d ' "' | sort -u || true)

            if [ -n "$file_images" ]; then
              IMAGES="$IMAGES"$'\n'"$file_images"
            fi
          done

          UNIQUE_IMAGES=$(echo "$IMAGES" | sort -u | grep -v '^$' || true)
          echo "Found images:"
          echo "$UNIQUE_IMAGES"

          echo "images<<EOF" >> $GITHUB_OUTPUT
          echo "$UNIQUE_IMAGES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Generate SBOM summary (lightweight)
        run: |
          mkdir -p sbom

          echo "# Software Bill of Materials (SBOM) Summary" > sbom/SUMMARY.md
          echo "" >> sbom/SUMMARY.md
          echo "Generated: $(date -u +%Y-%m-%d\ %H:%M:%S\ UTC)" >> sbom/SUMMARY.md
          echo "" >> sbom/SUMMARY.md
          echo "| Image | Components | Packages |" >> sbom/SUMMARY.md
          echo "|-------|------------|----------|" >> sbom/SUMMARY.md

          echo "${{ steps.extract-images.outputs.images }}" | while IFS= read -r image; do
            if [ -z "$image" ]; then
              continue
            fi

            echo "Analyzing $image..."

            # Generate lightweight summary only (no artifacts)
            component_count=$(syft "$image" -q -o json 2>/dev/null | jq '.artifacts | length' 2>/dev/null || echo "0")

            echo "| \`$image\` | $component_count | - |" >> sbom/SUMMARY.md
          done

      - name: Display SBOM summary
        run: |
          echo "SBOM Summary generated successfully"
          cat sbom/SUMMARY.md

      - name: Generate SBOM statistics
        run: |
          echo "# SBOM Generation Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          cat sbom/SUMMARY.md >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Note: Full SBOM generation runs weekly to conserve resources" >> $GITHUB_STEP_SUMMARY
